language: python
python:
    - "2.7"
before_install:
    - npm install jshint
install:
    - pip install django django-tastypie IXDjango lettuce mock pep8 pylint pylint_mccabe
script:
    .githooks/pre-commit -f
